Class {
	#name : #FamixTkMultipleFileAnchor,
	#superclass : #FamixTkSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkMultipleFileAnchor class >> annotation [

	<MSEClass: #MultipleFileAnchor super: #FamixTkSourceAnchor>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkMultipleFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixTkMultipleFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkMultipleFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTMultipleFileAnchor)
]

{ #category : #meta }
FamixTkMultipleFileAnchor class >> requirements [

	<generated>
	^ {  }
]
