Class {
	#name : #FamixTkIndexedFileAnchor,
	#superclass : #FamixTkAbstractFileAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkIndexedFileAnchor class >> annotation [

	<MSEClass: #IndexedFileAnchor super: #FamixTkAbstractFileAnchor>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkIndexedFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixTkIndexedFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkIndexedFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTIndexedFileNavigation)
]

{ #category : #meta }
FamixTkIndexedFileAnchor class >> requirements [

	<generated>
	^ {  }
]
