Class {
	#name : #FamixTkSourceLanguage,
	#superclass : #FamixTkEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkSourceLanguage class >> annotation [

	<MSEClass: #SourceLanguage super: #FamixTkEntity>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkSourceLanguage class >> generatedSlotNames [
	<generated>
	'FamixTkSourceLanguage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FamixTSourceLanguage)
]

{ #category : #meta }
FamixTkSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
