Class {
	#name : #FamixTkImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities'
}

{ #category : #generator }
FamixTkImportingContext class >> generatedSlotNames [
	<generated>
	'FamixTkImportingContext class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkImportingContext class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #testing }
FamixTkImportingContext >> importAbstractFile [

	<generated>
	^ self import: FamixTkAbstractFile
]

{ #category : #testing }
FamixTkImportingContext >> importAbstractFileAnchor [

	<generated>
	^ self import: FamixTkAbstractFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importAssociation [

	<generated>
	^ self import: FamixTkAssociation
]

{ #category : #testing }
FamixTkImportingContext >> importComment [

	<generated>
	^ self import: FamixTkComment
]

{ #category : #testing }
FamixTkImportingContext >> importEntity [

	<generated>
	^ self import: FamixTkEntity
]

{ #category : #testing }
FamixTkImportingContext >> importFile [

	<generated>
	^ self import: FamixTkFile
]

{ #category : #testing }
FamixTkImportingContext >> importFileAnchor [

	<generated>
	^ self import: FamixTkFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importFolder [

	<generated>
	^ self import: FamixTkFolder
]

{ #category : #testing }
FamixTkImportingContext >> importIndexedFileAnchor [

	<generated>
	^ self import: FamixTkIndexedFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importMultipleFileAnchor [

	<generated>
	^ self import: FamixTkMultipleFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importNamedEntity [

	<generated>
	^ self import: FamixTkNamedEntity
]

{ #category : #testing }
FamixTkImportingContext >> importSourceAnchor [

	<generated>
	^ self import: FamixTkSourceAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importSourceLanguage [

	<generated>
	^ self import: FamixTkSourceLanguage
]

{ #category : #testing }
FamixTkImportingContext >> importSourceTextAnchor [

	<generated>
	^ self import: FamixTkSourceTextAnchor
]

{ #category : #testing }
FamixTkImportingContext >> importSourcedEntity [

	<generated>
	^ self import: FamixTkSourcedEntity
]

{ #category : #testing }
FamixTkImportingContext >> importTicket [

	<generated>
	^ self import: FamixTkTicket
]

{ #category : #testing }
FamixTkImportingContext >> importTicketDependecy [

	<generated>
	^ self import: FamixTkTicketDependecy
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportAbstractFile [

	<generated>
	^ self shouldImport: FamixTkAbstractFile
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportAbstractFileAnchor [

	<generated>
	^ self shouldImport: FamixTkAbstractFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportAssociation [

	<generated>
	^ self shouldImport: FamixTkAssociation
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportComment [

	<generated>
	^ self shouldImport: FamixTkComment
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportEntity [

	<generated>
	^ self shouldImport: FamixTkEntity
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportFile [

	<generated>
	^ self shouldImport: FamixTkFile
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportFileAnchor [

	<generated>
	^ self shouldImport: FamixTkFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportFolder [

	<generated>
	^ self shouldImport: FamixTkFolder
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportIndexedFileAnchor [

	<generated>
	^ self shouldImport: FamixTkIndexedFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportMultipleFileAnchor [

	<generated>
	^ self shouldImport: FamixTkMultipleFileAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportNamedEntity [

	<generated>
	^ self shouldImport: FamixTkNamedEntity
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportSourceAnchor [

	<generated>
	^ self shouldImport: FamixTkSourceAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportSourceLanguage [

	<generated>
	^ self shouldImport: FamixTkSourceLanguage
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportSourceTextAnchor [

	<generated>
	^ self shouldImport: FamixTkSourceTextAnchor
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportSourcedEntity [

	<generated>
	^ self shouldImport: FamixTkSourcedEntity
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportTicket [

	<generated>
	^ self shouldImport: FamixTkTicket
]

{ #category : #testing }
FamixTkImportingContext >> shouldImportTicketDependecy [

	<generated>
	^ self shouldImport: FamixTkTicketDependecy
]
