Class {
	#name : #FamixTkAbstractFileAnchor,
	#superclass : #FamixTkSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkAbstractFileAnchor class >> annotation [

	<MSEClass: #AbstractFileAnchor super: #FamixTkSourceAnchor>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkAbstractFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixTkAbstractFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkAbstractFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTFileAnchor)
]

{ #category : #meta }
FamixTkAbstractFileAnchor class >> requirements [

	<generated>
	^ {  }
]
