Class {
	#name : #FamixTkSourceTextAnchor,
	#superclass : #FamixTkSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #FamixTkSourceAnchor>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'FamixTkSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTWithImmediateSource)
]

{ #category : #meta }
FamixTkSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]
