Class {
	#name : #FamixTkFileAnchor,
	#superclass : #FamixTkAbstractFileAnchor,
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : #'CIMTicketsAnalyseConstatGrammar-Entities-Entities'
}

{ #category : #meta }
FamixTkFileAnchor class >> annotation [

	<MSEClass: #FileAnchor super: #FamixTkAbstractFileAnchor>
	<package: #'CIMTicketsAnalyseConstatGrammar-Entities'>
	<generated>
	^self
]

{ #category : #generator }
FamixTkFileAnchor class >> generatedSlotNames [
	<generated>
	'FamixTkFileAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixTkFileAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTFileNavigation)
]

{ #category : #meta }
FamixTkFileAnchor class >> requirements [

	<generated>
	^ {  }
]
