Class {
	#name : #'Tbl_semaine_dev_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'semaine_id',
		'semaine_num',
		'semaine_cpt',
		'semaine_annee',
		'semaine_libelle',
		'semaine_debut',
		'semaine_fin'
	],
	#category : #CIMTicketsDataModel
}

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_annee [
	^ semaine_annee
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_annee: arg1 [
	semaine_annee := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_cpt [
	^ semaine_cpt
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_cpt: arg1 [
	semaine_cpt := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_debut [
	^ semaine_debut
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_debut: arg1 [
	semaine_debut := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_fin [
	^ semaine_fin
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_fin: arg1 [
	semaine_fin := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_id [
	^ semaine_id
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_id: arg1 [
	semaine_id := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_libelle [
	^ semaine_libelle
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_libelle: arg1 [
	semaine_libelle := arg1
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_num [
	^ semaine_num
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_num: arg1 [
	semaine_num := arg1
]
