Class {
	#name : #'Tbl_semaine_dev_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'semaine_id',
		'semaine_num',
		'semaine_cpt',
		'semaine_annee',
		'semaine_libelle',
		'semaine_debut',
		'semaine_fin'
	],
	#category : #'CIMTicketsDataModel-Model'
}

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_annee [
	^ semaine_annee
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_annee: anObject [
	semaine_annee := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_cpt [
	^ semaine_cpt
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_cpt: anObject [
	semaine_cpt := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_debut [
	^ semaine_debut
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_debut: anObject [
	semaine_debut := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_fin [
	^ semaine_fin
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_fin: anObject [
	semaine_fin := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_id [
	^ semaine_id
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_id: anObject [
	semaine_id := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_libelle [
	^ semaine_libelle
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_libelle: anObject [
	semaine_libelle := anObject
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_num [
	^ semaine_num
]

{ #category : #accessing }
Tbl_semaine_dev_row >> semaine_num: anObject [
	semaine_num := anObject
]
