Class {
	#name : #'Tbl_cim_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'cim_id',
		'cim_libelle',
		'cim_email',
		'cim_tel',
		'cim_telabrege',
		'cim_portable',
		'cim_portableabrege',
		'cim_securite_id',
		'cim_tps_dev',
		'cim_mail_qes_res',
		'cim_jour_envoi',
		'cim_plage_envoi'
	],
	#category : #'CIMTicketsDataModel-Model'
}

{ #category : #accessing }
Tbl_cim_row >> cim_email [
	^ cim_email
]

{ #category : #accessing }
Tbl_cim_row >> cim_email: anObject [
	cim_email := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_id [
	^ cim_id
]

{ #category : #accessing }
Tbl_cim_row >> cim_id: anObject [
	cim_id := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_jour_envoi [
	^ cim_jour_envoi
]

{ #category : #accessing }
Tbl_cim_row >> cim_jour_envoi: anObject [
	cim_jour_envoi := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_libelle [
	^ cim_libelle
]

{ #category : #accessing }
Tbl_cim_row >> cim_libelle: anObject [
	cim_libelle := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_mail_qes_res [
	^ cim_mail_qes_res
]

{ #category : #accessing }
Tbl_cim_row >> cim_mail_qes_res: anObject [
	cim_mail_qes_res := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_plage_envoi [
	^ cim_plage_envoi
]

{ #category : #accessing }
Tbl_cim_row >> cim_plage_envoi: anObject [
	cim_plage_envoi := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_portable [
	^ cim_portable
]

{ #category : #accessing }
Tbl_cim_row >> cim_portable: anObject [
	cim_portable := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_portableabrege [
	^ cim_portableabrege
]

{ #category : #accessing }
Tbl_cim_row >> cim_portableabrege: anObject [
	cim_portableabrege := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_securite_id [
	^ cim_securite_id
]

{ #category : #accessing }
Tbl_cim_row >> cim_securite_id: anObject [
	cim_securite_id := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_tel [
	^ cim_tel
]

{ #category : #accessing }
Tbl_cim_row >> cim_tel: anObject [
	cim_tel := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_telabrege [
	^ cim_telabrege
]

{ #category : #accessing }
Tbl_cim_row >> cim_telabrege: anObject [
	cim_telabrege := anObject
]

{ #category : #accessing }
Tbl_cim_row >> cim_tps_dev [
	^ cim_tps_dev
]

{ #category : #accessing }
Tbl_cim_row >> cim_tps_dev: anObject [
	cim_tps_dev := anObject
]
