Class {
	#name : #'Tbl_ft_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'ft_id',
		'ft_numordre',
		'ft_refclt',
		'ft_datecrea',
		'ft_priorite',
		'ft_test',
		'ft_type',
		'ft_etat',
		'ft_etatcommentaire',
		'ft_objet',
		'ft_constat',
		'ft_version_id',
		'ft_propo',
		'ft_resultsouhait',
		'ft_ddedevis',
		'ft_delaiprevu',
		'ft_delaisouhait',
		'ft_delaicommentaire',
		'ft_delaireel',
		'ft_delaiexpir',
		'ft_cc',
		'ft_facture_id',
		'ft_devis_id',
		'ft_modif_id',
		'ft_cim_id',
		'ft_clt_id',
		'ft_dossier_list',
		'ft_theme_id',
		'ft_lienft_list',
		'ft_dev_id',
		'ft_test_id',
		'ft_nonlu',
		'ft_hist_id',
		'ft_contexte',
		'ft_nbretour',
		'ft_attinfos',
		'ft_version_news',
		'ft_version_souhait',
		'ft_deplacement',
		'ft_typcorr_id',
		'ft_compta',
		'ft_nbretour_test',
		'ft_date_transfert',
		'ft_createur',
		'ft_sous_categorie_id',
		'ft_tnr'
	],
	#category : #'CIMTicketsDataModel-Model'
}

{ #category : #accessing }
Tbl_ft_row >> ft_attinfos [
	^ ft_attinfos
]

{ #category : #accessing }
Tbl_ft_row >> ft_attinfos: anObject [
	ft_attinfos := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_cc [
	^ ft_cc
]

{ #category : #accessing }
Tbl_ft_row >> ft_cc: anObject [
	ft_cc := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_cim_id [
	^ ft_cim_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_cim_id: anObject [
	ft_cim_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_clt_id [
	^ ft_clt_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_clt_id: anObject [
	ft_clt_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_compta [
	^ ft_compta
]

{ #category : #accessing }
Tbl_ft_row >> ft_compta: anObject [
	ft_compta := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_constat [
	^ ft_constat
]

{ #category : #accessing }
Tbl_ft_row >> ft_constat: anObject [
	ft_constat := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_contexte [
	^ ft_contexte
]

{ #category : #accessing }
Tbl_ft_row >> ft_contexte: anObject [
	ft_contexte := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_createur [
	^ ft_createur
]

{ #category : #accessing }
Tbl_ft_row >> ft_createur: anObject [
	ft_createur := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_date_transfert [
	^ ft_date_transfert
]

{ #category : #accessing }
Tbl_ft_row >> ft_date_transfert: anObject [
	ft_date_transfert := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_datecrea [
	^ ft_datecrea
]

{ #category : #accessing }
Tbl_ft_row >> ft_datecrea: anObject [
	ft_datecrea := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_ddedevis [
	^ ft_ddedevis
]

{ #category : #accessing }
Tbl_ft_row >> ft_ddedevis: anObject [
	ft_ddedevis := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaicommentaire [
	^ ft_delaicommentaire
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaicommentaire: anObject [
	ft_delaicommentaire := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaiexpir [
	^ ft_delaiexpir
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaiexpir: anObject [
	ft_delaiexpir := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaiprevu [
	^ ft_delaiprevu
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaiprevu: anObject [
	ft_delaiprevu := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaireel [
	^ ft_delaireel
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaireel: anObject [
	ft_delaireel := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaisouhait [
	^ ft_delaisouhait
]

{ #category : #accessing }
Tbl_ft_row >> ft_delaisouhait: anObject [
	ft_delaisouhait := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_deplacement [
	^ ft_deplacement
]

{ #category : #accessing }
Tbl_ft_row >> ft_deplacement: anObject [
	ft_deplacement := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_dev_id [
	^ ft_dev_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_dev_id: anObject [
	ft_dev_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_devis_id [
	^ ft_devis_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_devis_id: anObject [
	ft_devis_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_dossier_list [
	^ ft_dossier_list
]

{ #category : #accessing }
Tbl_ft_row >> ft_dossier_list: anObject [
	ft_dossier_list := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_etat [
	^ ft_etat
]

{ #category : #accessing }
Tbl_ft_row >> ft_etat: anObject [
	ft_etat := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_etatcommentaire [
	^ ft_etatcommentaire
]

{ #category : #accessing }
Tbl_ft_row >> ft_etatcommentaire: anObject [
	ft_etatcommentaire := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_facture_id [
	^ ft_facture_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_facture_id: anObject [
	ft_facture_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_hist_id [
	^ ft_hist_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_hist_id: anObject [
	ft_hist_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_id [
	^ ft_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_id: anObject [
	ft_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_lienft_list [
	^ ft_lienft_list
]

{ #category : #accessing }
Tbl_ft_row >> ft_lienft_list: anObject [
	ft_lienft_list := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_modif_id [
	^ ft_modif_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_modif_id: anObject [
	ft_modif_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_nbretour [
	^ ft_nbretour
]

{ #category : #accessing }
Tbl_ft_row >> ft_nbretour: anObject [
	ft_nbretour := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_nbretour_test [
	^ ft_nbretour_test
]

{ #category : #accessing }
Tbl_ft_row >> ft_nbretour_test: anObject [
	ft_nbretour_test := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_nonlu [
	^ ft_nonlu
]

{ #category : #accessing }
Tbl_ft_row >> ft_nonlu: anObject [
	ft_nonlu := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_numordre [
	^ ft_numordre
]

{ #category : #accessing }
Tbl_ft_row >> ft_numordre: anObject [
	ft_numordre := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_objet [
	^ ft_objet
]

{ #category : #accessing }
Tbl_ft_row >> ft_objet: anObject [
	ft_objet := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_priorite [
	^ ft_priorite
]

{ #category : #accessing }
Tbl_ft_row >> ft_priorite: anObject [
	ft_priorite := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_propo [
	^ ft_propo
]

{ #category : #accessing }
Tbl_ft_row >> ft_propo: anObject [
	ft_propo := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_refclt [
	^ ft_refclt
]

{ #category : #accessing }
Tbl_ft_row >> ft_refclt: anObject [
	ft_refclt := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_resultsouhait [
	^ ft_resultsouhait
]

{ #category : #accessing }
Tbl_ft_row >> ft_resultsouhait: anObject [
	ft_resultsouhait := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_sous_categorie_id [
	^ ft_sous_categorie_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_sous_categorie_id: anObject [
	ft_sous_categorie_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_test [
	^ ft_test
]

{ #category : #accessing }
Tbl_ft_row >> ft_test: anObject [
	ft_test := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_test_id [
	^ ft_test_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_test_id: anObject [
	ft_test_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_theme_id [
	^ ft_theme_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_theme_id: anObject [
	ft_theme_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_tnr [
	^ ft_tnr
]

{ #category : #accessing }
Tbl_ft_row >> ft_tnr: anObject [
	ft_tnr := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_typcorr_id [
	^ ft_typcorr_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_typcorr_id: anObject [
	ft_typcorr_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_type [
	^ ft_type
]

{ #category : #accessing }
Tbl_ft_row >> ft_type: anObject [
	ft_type := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_id [
	^ ft_version_id
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_id: anObject [
	ft_version_id := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_news [
	^ ft_version_news
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_news: anObject [
	ft_version_news := anObject
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_souhait [
	^ ft_version_souhait
]

{ #category : #accessing }
Tbl_ft_row >> ft_version_souhait: anObject [
	ft_version_souhait := anObject
]

{ #category : #initialization }
Tbl_ft_row >> initializeWith: aDictionary [
	super initializeWith: aDictionary.
	ft_datecrea ifNil: [ ^ self ].
	ft_datecrea := ft_datecrea asDate
]
