Class {
	#name : #'Tbl_version_news_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'versionn_id',
		'versionn_libelle',
		'versionn_ordre'
	],
	#category : #CIMTicketsDataModel
}

{ #category : #accessing }
Tbl_version_news_row >> versionn_id [
	^ versionn_id
]

{ #category : #accessing }
Tbl_version_news_row >> versionn_id: anObject [
	versionn_id := anObject
]

{ #category : #accessing }
Tbl_version_news_row >> versionn_libelle [
	^ versionn_libelle
]

{ #category : #accessing }
Tbl_version_news_row >> versionn_libelle: anObject [
	versionn_libelle := anObject
]

{ #category : #accessing }
Tbl_version_news_row >> versionn_ordre [
	^ versionn_ordre
]

{ #category : #accessing }
Tbl_version_news_row >> versionn_ordre: anObject [
	versionn_ordre := anObject
]
