Class {
	#name : #'Tbl_type_session_row',
	#superclass : #'Tbl_row',
	#instVars : [
		'typsession_id',
		'typsession_libelle',
		'typsession_abrege',
		'typsession_descriptif',
		'typsession_code',
		'typsession_couleur',
		'typsession_type',
		'typsession_sai_standard',
		'typsession_sai_deplacement',
		'typsession_sai_devis',
		'typsession_ordre'
	],
	#category : #'CIMTicketsDataModel-Model'
}

{ #category : #accessing }
Tbl_type_session_row >> typsession_abrege [
	^ typsession_abrege
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_abrege: anObject [
	typsession_abrege := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_code [
	^ typsession_code
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_code: anObject [
	typsession_code := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_couleur [
	^ typsession_couleur
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_couleur: anObject [
	typsession_couleur := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_descriptif [
	^ typsession_descriptif
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_descriptif: anObject [
	typsession_descriptif := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_id [
	^ typsession_id
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_id: anObject [
	typsession_id := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_libelle [
	^ typsession_libelle
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_libelle: anObject [
	typsession_libelle := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_ordre [
	^ typsession_ordre
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_ordre: anObject [
	typsession_ordre := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_deplacement [
	^ typsession_sai_deplacement
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_deplacement: anObject [
	typsession_sai_deplacement := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_devis [
	^ typsession_sai_devis
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_devis: anObject [
	typsession_sai_devis := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_standard [
	^ typsession_sai_standard
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_sai_standard: anObject [
	typsession_sai_standard := anObject
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_type [
	^ typsession_type
]

{ #category : #accessing }
Tbl_type_session_row >> typsession_type: anObject [
	typsession_type := anObject
]
