name: Github Actions build  

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [  macos-latest ]
        smalltalk:
          - Pharo64-8.0 
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Run smalltalkCI self test
        run: smalltalkci -s ${{ matrix.smalltalk }} --self-test
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#Coverall
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-${{matrix.smalltalk}}
  #        parallel: true
  # finish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Coveralls Finished
  #     uses: coverallsapp/github-action@master
  #     with:
  #       github-token: ${{ secrets.github_token }}
  #       parallel-finished: true
